<script src="../jquery/jquery-3.2.1.min.js"></script>
<script src="../jquery/moment.min.js"></script>
<script src="../jquery/bootstrap-datetimepicker.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDX-mBBK_AjTs-t2_NsF1Nv8Ax52MWJ1yM&callback=initMap"></script>
<script src="../jquery/popper.js"></script>
<script src="../jquery/bootstrap.js"></script>
<script src="../jquery/jquery-ui.js"></script>
<script src="../jquery/geolocation-marker.js"></script>
<script src="../jquery/autocomplete.js"></script>
<script src="../jquery/select2.min.js"></script>
<script src="../jquery/jquery.dataTables.js"></script>
<script src="../jquery/feather-icon/feather.min.js"></script>
